### ISSUE TITLE
Reevaluate default resource requests

### ISSUE THREAD

**Issue by simu** [projectsyn/component-rook-ceph#73]
## Context

We've seen that the Ceph cluster doesn't really use the resources we request during normal operation, requiring us to provision relatively large storage nodes, which are then mostly idle. This is not great for financial reasons. We should reevaluate the component's default resource requests and limits based on actual usage numbers from production environments.

Since Rook now provides a ceph-cluster Helm chart which defines default resource requests for the Ceph components, we should also check if those default requests are suitable for us. See https://github.com/rook/rook/blob/1ae867049b49079b76696e68ee9b8f30216528bd/deploy/charts/rook-ceph-cluster/values.yaml#L233-L289

## Alternatives

Don't do anything.

**Comment by bastjan** [comment]
New default requests are more or less the recommended minimum https://github.com/rook/rook/issues/9858#issuecomment-1064354946 with a small increase for the `prepareosd` pod https://github.com/rook/rook/commit/bf1342b2b303ca204906f01ed5f43bacd338ad27 (https://github.com/rook/rook/issues/10477).

**Comment by bastjan** [comment]
![image](https://user-images.githubusercontent.com/1249775/188447353-ce8ab5d3-0fdb-4c6c-ae72-f8d325920b2b.png)

CPU load seems to spike pretty aggressively. Not sure if we should lessen CPU defaults.

**Comment by bastjan** [comment]
![Screenshot 2022-09-05 at 15 32 47](https://user-images.githubusercontent.com/1249775/188463310-1c4acd6d-9ac6-4001-baf0-84106ffba21a.png)


MDS daemons already get OOMKilled from time to time with limits 8GB.

```yaml
  - containerID: ...
    image: quay.io/ceph/ceph:v16.2.9
    lastState:
      terminated:
        exitCode: 137
        finishedAt: "2022-09-02T07:02:56Z"
        reason: OOMKilled
        startedAt: "2022-08-16T12:21:09Z"
    name: mds
```
